In [ ]:
QUESTION 1:

In [1]:
import numpy as np
arr=np.arange(start=2, stop=50, step=3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [ ]:
QUESTION 2:

In [2]:
import numpy as np
list1 = [0,2,4,6,8] 
list2 = [1,3,5,7,9]
arr =np.array(list1)
arr1 =np.array(list2)
print(" #Printing array ")
print(arr)
print(arr1)
print("\n\n #Concatenating two arrays")
arr2 =np.concatenate((arr,arr1), axis=None)
print(arr2)

print("\n\n #Sorting the concatenated array")
print(np.sort(arr2))


 #Printing array 
[0 2 4 6 8]
[1 3 5 7 9]


 #Concatenating two arrays
[0 2 4 6 8 1 3 5 7 9]


 #Sorting the concatenated array
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
QUESTION 3:

In [3]:
import numpy as np
x =np.array([[1,2,3],[4,5,6]])
print(x)
print("\n\n Dimension of array")
Y=x.shape
print(Y)
print("\n\n Size of array")
x.size

[[1 2 3]
 [4 5 6]]


 Dimension of array
(2, 3)


 Size of array


6

In [ ]:
QUESTION 4:

In [4]:
import numpy as np
arr =np.array([0,1,2,3,4,5,6,7,8,9])
arr_2d = np.reshape(arr, (2, 5))
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
QUESTION 5:

In [5]:
import numpy as np
arr = np.array([1,2,3])
arr1= np.array([4,5,6])

print("Horizontal stack :") 
x=np.hstack((arr, arr1))
print(x)
print("\n\n Vertical stack :")
np.vstack((arr,arr1))

Horizontal stack :
[1 2 3 4 5 6]


 Vertical stack :


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
QUESTION 6:

In [6]:
import numpy as np
arr = np.array([1,1,2,3,4,5,5,6,7,7,8])
unique_values=np.unique(arr)
print(unique_values)

[1 2 3 4 5 6 7 8]
